// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzqpafnstmnwcmcweokz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cXBhZm5zdG1ud2NtY3dlb2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzg1ODEsImV4cCI6MjA3Mjc1NDU4MX0.6mCOQM1mcjQIlXyIAEtg76s1psg6ZxCeYMEX9OQd4R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});